### ISSUE TITLE
Error deactivating package 'file-watcher' TypeError: Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by Arcanemagus** [lwblackledge/file-watcher#16] opened 2016-10-14 23:25 UTC
Whenever Atom gets reloaded or the package is disabled I see the following stack trace in the console:

```
Error deactivating package 'file-watcher' TypeError: Cannot read property 'destroy' of undefined
    at FileWatcherInitializer.deactivate (file:///C:/Users/Landon Abney/.atom/packages/file-watcher/lib/init.coffee:39:16)
    at Package.module.exports.Package.deactivate (C:\Users\Landon Abney\AppData\Local\atom\app-1.12.0-beta1\resources\app.asar\src\package.js:668:20)
    at PackageManager.module.exports.PackageManager.deactivatePackage (C:\Users\Landon Abney\AppData\Local\atom\app-1.12.0-beta1\resources\app.asar\src\package-manager.js:632:12)
    at C:\Users\Landon Abney\AppData\Local\atom\app-1.12.0-beta1\resources\app.asar\src\package-manager.js:618:19
    at Config.module.exports.Config.transact (C:\Users\Landon Abney\AppData\Local\atom\app-1.12.0-beta1\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.deactivatePackages (C:\Users\Landon Abney\AppData\Local\atom\app-1.12.0-beta1\resources\app.asar\src\package-manager.js:612:19)
    at AtomEnvironment.module.exports.AtomEnvironment.unloadEditorWindow (C:\Users\Landon Abney\AppData\Local\atom\app-1.12.0-beta1\resources\app.asar\src\atom-environment.js:815:21)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBeforeunload (C:\Users\Landon Abney\AppData\Local\atom\app-1.12.0-beta1\resources\app.asar\src\window-event-handler.js:212:30)
    at C:\Users\Landon Abney\AppData\Local\atom\app-1.12.0-beta1\resources\app.asar\src\window-event-handler.js:3:59
```

Currently seeing this on Atom v1.12.0-beta1, but I've been seeing it for a while.

**Comment by lwblackledge** [comment] 2017-01-20 01:25
I have a fix for this in the next release (and I forgot, so that explains why I cannot reproduce it).

**Closed as completed** 2017-01-21 13:24 UTC
Labels: bug
