### ISSUE TITLE
Reload closes file instead of reloading

### ISSUE THREAD

**Issue by briansuhr** [lwblackledge/file-watcher#19] opened 2017-03-08 04:37 UTC
file-watcher prompts that a file has changed, but clicking Reload (or using Reload Automatically) closes the  file without reloading.

**Comment by lwblackledge** [comment] 2017-03-09 21:52
I cannot reproduce this one. Can you give me some more info?

- OS
- Atom version
- File system
- Selected file-watcher options

Thanks.

**Comment by briansuhr** [comment] 2017-03-10 06:16
OS: Windows 10
Atom version: 1.15.0
File system: NTFS
File-watcher options: Default

I did some more testing and narrowed the problem down to gVim, which I was using to update the files open in Atom. file-watcher worked correctly if I updated the same file through Emacs or Notepad. 

I guess Atom is getting confused with the files gVim is saving. Doing something different with line endings maybe?

**Comment by lwblackledge** [comment] 2017-03-10 22:14
Ah there was a similar issue with some of the Jetbrains editors (#14). I am guessing the gVim is like vim (no, really?) and does not actually overwrite when saving a file. Instead it probably saves as `filename.txt~` then renames, to prevent issues when crashing.

The ever useful [stackoverflow.com](http://stackoverflow.com/questions/607435/why-does-vim-save-files-with-a-extension) offered up this solution, although it is not recommended:

```
set nobackup       #no backup files
set nowritebackup  #only in case you don't want a backup file while editing
set noswapfile     #no swap files
```

I can't do much about it from a package perspective though, sorry. I will close this as `wontfix`.

**Closed as completed by lwblackledge** 2017-03-10 22:14 UTC
Labels: wontfix

**Comment by briansuhr** [comment] 2017-03-10 22:18
Yep, I think that is exactly what's happening. Good call. Sorry to jump the gun.

**Comment by lwblackledge** [comment] 2017-03-10 22:19
No problem. The solution is not ideal since there is a reason vim does this but maybe those options will work for you while you are working on files with both editors.
